---
services:
  bert:
    container_name: bert
    build: bot
    image: codeman1o1/bert
    env_file:
      - .env
    depends_on:
      pocketbase:
        condition: service_healthy
      lavalink:
        condition: service_healthy
      ai:
        condition: service_started
    restart: unless-stopped

  website:
    container_name: bert-website
    build: website
    image: codeman1o1/bertsite
    ports:
      - "6969:3000"
    env_file:
      - .env
    restart: unless-stopped

  pocketbase:
    container_name: bert-pocketbase
    build:
      context: pocketbase
      args:
        - VERSION=0.22.10
        - PB_EMAIL=${PB_EMAIL}
        - PB_PASSWORD=${PB_PASSWORD}
    image: codeman1o1/bert-pocketbase
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 1s
      timeout: 2s
      retries: 5
    env_file:
      - .env
    ports:
      - 8090:8090
    volumes:
      - pocketbase:/pb_data
      - ./pocketbase/pb_data/types.d.ts:/pb_data/types.d.ts
      - ./pocketbase/migrations:/pb_migrations
    restart: unless-stopped

  lavalink:
    container_name: bert-lavalink
    image: ghcr.io/lavalink-devs/lavalink:4-alpine
    healthcheck:
      test: nc -z localhost 2333
      start_period: 3s
      interval: 2s
      timeout: 2s
      retries: 5
    env_file:
      - .env
    environment:
      - _JAVA_OPTIONS=-Xmx3G
      - SERVER_PORT=2333
      - LAVALINK_SERVER_PASSWORD=${LAVALINK_PASSWORD}
    volumes:
      - ./lavalink.yml:/opt/Lavalink/application.yml
      - ./bot/sounds:/opt/Lavalink/sounds
    restart: unless-stopped

  ai:
    container_name: bert-ai
    image: ollama/ollama
    volumes:
      - ai:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped

volumes:
  pocketbase:
  ai:
