---
version: "2.4"
services:
  bert:
    container_name: bert
    build: "./bot"
    image: codeman1o1/bert
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      lavalink:
        condition: service_healthy
      ai:
        condition: service_started
    restart: unless-stopped

  website:
    container_name: bert-website
    build: "./website"
    image: codeman1o1/bertsite
    ports:
      - "6969:3000"
    env_file:
      - .env
    restart: unless-stopped

  lavalink:
    container_name: bert-lavalink
    image: ghcr.io/lavalink-devs/lavalink:4-alpine
    healthcheck:
      test: "netstat -ltn | grep -c ':2333'"
      interval: 2s
      timeout: 10s
      retries: 5
    env_file:
      - .env
    environment:
      - _JAVA_OPTIONS=-Xmx3G
      - SERVER_PORT=2333
      - LAVALINK_SERVER_PASSWORD=${LAVALINK_PASSWORD}
    restart: unless-stopped

  db:
    container_name: bert-db
    image: postgres:16-alpine
    healthcheck:
      test: "pg_isready -U bert -d bert"
      interval: 2s
      timeout: 10s
      retries: 5
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
      - bertdb:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_USER=bert
      - POSTGRES_DB=bert
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    restart: unless-stopped

  ai:
    container_name: bert-ai
    image: ollama/ollama
    volumes:
      - bertai:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped

volumes:
  bertdb:
  bertai:
