---
name: Lint
permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - bot/**
      - website/**
  pull_request:
    branches:
      - main
    paths:
      - bot/**
      - website/**

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Install Node.js
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: |
          cd website
          bun ci

      - name: Run ESLint
        run: |
          cd website
          bun run lint

  ruff:
    name: Ruff
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Install Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Run Ruff
        run: |
          cd bot
          ruff check --output-format=github .
          ruff format --check .
